[lists]
block = [
  "https://urlhaus.abuse.ch/downloads/hostfile/",
  "https://hole.cert.pl/domains/domains.txt",
  "https://raw.githubusercontent.com/cenk/trcert-malware/main/trcert-domains.txt",
  "https://raw.githubusercontent.com/FiltersHeroes/KADhosts/master/KADhosts.txt",
  "https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt",
  "https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt",
  "https://threatfox.abuse.ch/downloads/hostfile",
  "https://raw.githubusercontent.com/Zaczero/pihole-phishtank/main/hosts.txt",
  "https://lists.cyberhost.uk/malware.txt",
  "https://media.githubusercontent.com/media/zachlagden/Pi-hole-Optimized-Blocklists/refs/heads/main/lists/malicious.txt",
  "https://phishing.army/download/phishing_army_blocklist.txt",
  "https://blocklistproject.github.io/Lists/crypto.txt",
  "https://blocklistproject.github.io/Lists/fraud.txt",
  "https://blocklistproject.github.io/Lists/malware.txt",
  "https://blocklistproject.github.io/Lists/phishing.txt",
  "https://blocklistproject.github.io/Lists/ransomware.txt",
  "https://blocklistproject.github.io/Lists/scam.txt",
  "https://sslbl.abuse.ch/blacklist/sslipblacklist.txt",
  "https://openphish.com/feed.txt",
  "https://raw.githubusercontent.com/FiltersHeroes/KADhosts/master/KADhosts.txt
  ]
